# -*- coding: utf-8 -*-
"""project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xIbjGxf4Lih-6Ass8IL7C7fqeuPmcWNS
"""

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
import joblib

df=pd.read_csv('credit_card.csv')
df.head()

df.info()

df.isnull().mean()*100

df.dropna(inplace=True)

df.isnull().sum()

df['Class'].value_counts()

x=df.drop(['Class'],axis='columns')
y=df['Class']
x_train,x_test,y_train,y_train = train_test_split(x,y,test_size=0.2,random_state=42)

x.shape

y.shape

from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
model = LogisticRegression()
model.fit(x_train, y_train)
pred = model.predict(x_test)
score = model.score(x_test, y_test)
print("Accuracy:", score)

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
model = SVC()
model.fit(x_train, y_train)
pred = model.predict(x_test)
score = model.score(x_test, y_test)
print("Accuracy:", score)

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)
rf = RandomForestClassifier(class_weight='balanced', random_state=42)
rf.fit(x_train, y_train)
pred = rf.predict(x_test)
score = rf.score(x_test, y_test)
print("Accuracy:", score)

joblib.dump(rf,'model.pkl')